version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: seo-analysis-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - backend_cache:/root/.cache
    networks:
      - seo-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: seo-analysis-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - seo-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

networks:
  seo-network:
    driver: bridge

volumes:
  backend_cache:
  node_modules:
